set_property PACKAGE_PIN V12 [get_ports SM1]
set_property PACKAGE_PIN W10 [get_ports SM2]
set_property PACKAGE_PIN V9 [get_ports SM3]
set_property PACKAGE_PIN V8 [get_ports SM4]
set_property PACKAGE_PIN Y9 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports SM1]
set_property IOSTANDARD LVCMOS33 [get_ports SM2]
set_property IOSTANDARD LVCMOS33 [get_ports SM3]
set_property IOSTANDARD LVCMOS33 [get_ports SM4]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN F22 [get_ports power_switch]
set_property PACKAGE_PIN G22 [get_ports direction_switch]
set_property IOSTANDARD LVCMOS33 [get_ports direction_switch]
set_property IOSTANDARD LVCMOS33 [get_ports power_switch]

